---
- block:
  - name: Fail when timer_command is undefined
    fail:
      msg: Variable timer_command is not defined
    when: item.value.timer_command is undefined
    with_dict: '{{ timers }}'

  - name: Upload service file
    template:
      src: service.j2
      dest: '{{ basedir }}/{{ item.key }}.service'
      owner: '{{ owner }}'
      group: '{{ group }}'
      mode: 0644
    with_dict: '{{ timers }}'
    notify: Reload systemd

  - name: Upload timer file
    template:
      src: timer.j2
      dest: '{{ basedir }}/{{ item.key }}.timer'
      owner: '{{ owner }}'
      group: '{{ group }}'
      mode: 0644
    with_dict: '{{ timers }}'
    notify: Reload systemd

  - name: Enable timers
    systemd:
      name: '{{ item.key }}.timer'
      state: started
      enabled: true
      masked: false
      daemon_reload: true
    with_dict: '{{ timers }}'

  when: timers is defined
  vars:
    basedir: "{{ '/home/{{ USER }}' if item.userspace else '/etc/systemd/system' }}"
    owner: "{{ {{ USER }} if item.value.userspace else 'root' }}"
    group: "{{ {{ USER }} if item.value.userspace else 'root' }}"

